name: Azure Static Web App Deploy

on:
  push:
    branches:
      - main  # Change this if your branch is different

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy static site to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'Bigdata'        # Your Azure Web App name
        slot-name: 'production'    # Default deployment slot
        package: '.'               # Location of your static website files
